namespace Project.CSS.Revise.Web.Models
{
    public class ViewTempBlkUnit
    {
        public string PFREPRJNOSAP { get; set; }
        public string FREPRJNM { get; set; }
        public string Fcat1 { get; set; }
        public string FREPRJNO { get; set; }
        public string FSERIALNO { get; set; }
        public string FPDCODE { get; set; }
        public string FAGRNO { get; set; }
        public string FTYUNIT { get; set; }
        public Nullable<System.DateTime> FFINDATE { get; set; }
        public Nullable<System.DateTime> FRECDATE { get; set; }
        public Nullable<System.DateTime> FDUEDATE { get; set; }
        public Nullable<int> fconcdate { get; set; }
        public Nullable<int> fconfdate { get; set; }
        public Nullable<int> fconafdate { get; set; }
        public Nullable<int> fconudate { get; set; }
        public Nullable<decimal> FTPRICE { get; set; }
        public decimal Ftprice2 { get; set; }
        public decimal FASCOSTAMT { get; set; }
        public Nullable<decimal> Pkscchamt { get; set; }
        public Nullable<decimal> Pkscostamt { get; set; }
        public decimal Pksprice { get; set; }
        public string FRESTATUS { get; set; }
        public Nullable<System.DateTime> BOOKDATE { get; set; }
        public Nullable<System.DateTime> AGRDATE { get; set; }
        public Nullable<System.DateTime> TRANSDATE { get; set; }
        public string FBOOKNO { get; set; }
        public Nullable<System.DateTime> BOOKDATE2 { get; set; }
        public string FADDRNO { get; set; }
        public string FCUCODE { get; set; }
        public string FCUNAME { get; set; }
        public string FTEL { get; set; }
        public string FRECRSCD { get; set; }
        public Nullable<int> FAGRTERMS { get; set; }
        public Nullable<decimal> FRENTAL { get; set; }
        public Nullable<decimal> FNRFAMT { get; set; }
        public Nullable<decimal> FRFDAMT { get; set; }
        public string FSMNAME { get; set; }
        public Nullable<System.DateTime> FACTDATE { get; set; }
        public string FCRDBANK { get; set; }
        public Nullable<decimal> FCRDAMT { get; set; }
        public Nullable<decimal> FCRDAPAMT { get; set; }
        public Nullable<System.DateTime> FCRDAPDT { get; set; }
        public Nullable<int> FWHOASS { get; set; }
        public string FSUNAME { get; set; }
        public Nullable<decimal> FQTY { get; set; }
        public Nullable<decimal> FAREA { get; set; }
        public Nullable<System.DateTime> FAGRFROM { get; set; }
        public Nullable<System.DateTime> FAGRTO { get; set; }
        public string Pksagrno { get; set; }
        public string FADD1 { get; set; }
        public string FADD2 { get; set; }
        public string FADD3 { get; set; }
        public string FPROVINCE { get; set; }
        public string FPOSTAL { get; set; }
        public string FTELNO { get; set; }
        public string FREPHASE { get; set; }
        public string PSubphase { get; set; }
        public string fconsee { get; set; }
        public string FREBLOCK { get; set; }
        public Nullable<System.DateTime> Zfagrdateks { get; set; }
        public Nullable<System.DateTime> Zfmdateks { get; set; }
        public string FDOCSTATUS { get; set; }
        public string FUPDFLAG { get; set; }
        public Nullable<int> FRECRSCD2 { get; set; }
        public Nullable<decimal> FADISC { get; set; }
        public Nullable<decimal> FADISCKS { get; set; }
        public Nullable<decimal> FTOVERAREA { get; set; }
        public string FCONTCODE { get; set; }
        public string FCONTTNM { get; set; }
        public string FPACKAGE { get; set; }
        public Nullable<int> PlanQC5Date { get; set; }
        public string Freprjnm2 { get; set; }
        public Nullable<System.DateTime> FCRDDATE { get; set; }
        public string CusID { get; set; }
        public Nullable<decimal> BuiltInLand { get; set; }
        public Nullable<decimal> BuiltInAmt { get; set; }
        public string CustomerEmail { get; set; }
        public int OverDuePeriod { get; set; }
        public decimal OverDueAmount { get; set; }
        public decimal FreeAll { get; set; }
        public decimal TransferNetPrice { get; set; }
    }
}
